[deploy]
startCommand = "touch /app/database/database.sqlite && php artisan migrate --force && php artisan db:seed --force && php artisan optimize:clear && php artisan optimize && frankenphp run --config /Caddyfile"
